version: "3"
volumes:
  node_modules:
services:
  preact-bug-dev:
    build: .devcontainer
    container_name: preact-bug-dev
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
